/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Diego Sebastian
 */
public class frmOperacionStock extends MasterJInternalFrame {

    /**
     * Creates new form frmOperacionStock
     */
    public frmOperacionStock() {
        initComponents();
        setContentAreaFilledToButtons();
        jTblStock.setAutoscrolls(true);
        //new JScrollPane(jTblStock, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        //jTblStock.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTblStock.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTblStock1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jBtnEntrada = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        jBtnSalida = new javax.swing.JButton();
        jBtnConfiguracion = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jBtnImprimir = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblStock = new javax.swing.JTable();

        jTblStock1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTblStock1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripción", "Código", "Stock Actual", "Stock reservado", "Stock disponible", "Precio", "Categoría", "Unidad", "Principal proveedor", "Código ref.", "Marca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblStock1.setRowHeight(25);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));

        jBtnEntrada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBtnEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/entrada_32.png"))); // NOI18N
        jBtnEntrada.setText("Entrada");
        jBtnEntrada.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jBtnEntrada.setPreferredSize(new java.awt.Dimension(65, 65));
        jBtnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEntradaActionPerformed(evt);
            }
        });

        jBtnEditar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/resumen_32.png"))); // NOI18N
        jBtnEditar.setText("Editar");

        jBtnSalida.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBtnSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/salida_32.png"))); // NOI18N
        jBtnSalida.setText("Salida");
        jBtnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalidaActionPerformed(evt);
            }
        });

        jBtnConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/configuraciones_32.png"))); // NOI18N
        jBtnConfiguracion.setPreferredSize(new java.awt.Dimension(65, 65));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jBtnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/impresion_32.png"))); // NOI18N
        jBtnImprimir.setText("Imprimir recibo");
        jBtnImprimir.setPreferredSize(new java.awt.Dimension(65, 65));

        jBtnCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/prohibido_32.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jBtnEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jBtnConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator4)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator1)
                                        .addComponent(jBtnConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(jBtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jBtnEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jBtnSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jSeparator3)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(8, 8, 8))
        );

        jTblStock.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTblStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Número", "Fecha", "Hora", "Cliente / Proveedor", "Total Final", "Observaciones", "Empleado", "Vendedor", "SubTotal", "Descuento", "Otros gastos", "Flete", "Valor pagado", "Medio de pago", "Saldo a favor", "En deuda", "Vuelto", "Acreditado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblStock.setRowHeight(25);
        jScrollPane1.setViewportView(jTblStock);
        if (jTblStock.getColumnModel().getColumnCount() > 0) {
            jTblStock.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTblStock.getColumnModel().getColumn(1).setMinWidth(80);
            jTblStock.getColumnModel().getColumn(1).setPreferredWidth(80);
            jTblStock.getColumnModel().getColumn(2).setMinWidth(80);
            jTblStock.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTblStock.getColumnModel().getColumn(3).setMinWidth(80);
            jTblStock.getColumnModel().getColumn(3).setPreferredWidth(80);
            jTblStock.getColumnModel().getColumn(4).setMinWidth(150);
            jTblStock.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTblStock.getColumnModel().getColumn(5).setMinWidth(95);
            jTblStock.getColumnModel().getColumn(5).setPreferredWidth(95);
            jTblStock.getColumnModel().getColumn(6).setMinWidth(150);
            jTblStock.getColumnModel().getColumn(6).setPreferredWidth(150);
            jTblStock.getColumnModel().getColumn(7).setMinWidth(95);
            jTblStock.getColumnModel().getColumn(7).setPreferredWidth(95);
            jTblStock.getColumnModel().getColumn(8).setMinWidth(110);
            jTblStock.getColumnModel().getColumn(8).setPreferredWidth(110);
            jTblStock.getColumnModel().getColumn(9).setMinWidth(80);
            jTblStock.getColumnModel().getColumn(9).setPreferredWidth(80);
            jTblStock.getColumnModel().getColumn(10).setMinWidth(80);
            jTblStock.getColumnModel().getColumn(10).setPreferredWidth(80);
            jTblStock.getColumnModel().getColumn(11).setMinWidth(100);
            jTblStock.getColumnModel().getColumn(11).setPreferredWidth(100);
            jTblStock.getColumnModel().getColumn(12).setMinWidth(80);
            jTblStock.getColumnModel().getColumn(12).setPreferredWidth(80);
            jTblStock.getColumnModel().getColumn(13).setMinWidth(100);
            jTblStock.getColumnModel().getColumn(13).setPreferredWidth(100);
            jTblStock.getColumnModel().getColumn(14).setMinWidth(100);
            jTblStock.getColumnModel().getColumn(14).setPreferredWidth(100);
            jTblStock.getColumnModel().getColumn(15).setMinWidth(100);
            jTblStock.getColumnModel().getColumn(15).setPreferredWidth(100);
            jTblStock.getColumnModel().getColumn(16).setMinWidth(90);
            jTblStock.getColumnModel().getColumn(16).setPreferredWidth(90);
            jTblStock.getColumnModel().getColumn(17).setMinWidth(90);
            jTblStock.getColumnModel().getColumn(17).setPreferredWidth(90);
            jTblStock.getColumnModel().getColumn(18).setMinWidth(90);
            jTblStock.getColumnModel().getColumn(18).setPreferredWidth(90);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEntradaActionPerformed

    }//GEN-LAST:event_jBtnEntradaActionPerformed

    private void jBtnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalidaActionPerformed

    }//GEN-LAST:event_jBtnSalidaActionPerformed

    @Override
    public void onChildClosing() {

    }

    private void setContentAreaFilledToButtons() {
        jBtnConfiguracion.setContentAreaFilled(false);
        jBtnEditar.setContentAreaFilled(false);
        jBtnImprimir.setContentAreaFilled(false);
        jBtnCancelar.setContentAreaFilled(false);
        jBtnEntrada.setContentAreaFilled(false);
        jBtnSalida.setContentAreaFilled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfiguracion;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnEntrada;
    private javax.swing.JButton jBtnImprimir;
    private javax.swing.JButton jBtnSalida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTblStock;
    private javax.swing.JTable jTblStock1;
    // End of variables declaration//GEN-END:variables
}
