/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import components.JInternalFrameCustom;
import java.awt.Color;
import java.awt.Dimension;
import java.util.HashMap;
import javax.swing.JInternalFrame;

/**
 *
 * @author Diego Sebastian
 */
public class frmProductos extends JInternalFrameCustom {

    private static final java.awt.Color COLOR_BTN_ACTIVO = Color.getHSBColor(128, 255, 128);

    private enum Formularios {
        PRODUCTOS,
        STOCK,
        INVENTARIO,
        PROVEEDORES;
    }

    private static HashMap<Formularios, JInternalFrame> mapFormularios = new HashMap<>();

    /**
     * Creates new form frmProductos
     */
    public frmProductos() {
        initComponents();
        inicializar();
        this.irAProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnProductos = new components.SquareButton();
        jBtnStock = new components.SquareButton();
        jBtnProveedores = new components.SquareButton();
        jBtnInventario = new components.SquareButton();
        jInternalFramePrincipal = new JInternalFrameCustom();

        jBtnProductos.setText("Productos");
        jBtnProductos.setFocusable(false);
        jBtnProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProductosActionPerformed(evt);
            }
        });

        jBtnStock.setText("Operaciones de Stock");
        jBtnStock.setFocusable(false);
        jBtnStock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnStock.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnStockActionPerformed(evt);
            }
        });

        jBtnProveedores.setText("Proveedores");
        jBtnProveedores.setFocusable(false);
        jBtnProveedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnProveedores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProveedoresActionPerformed(evt);
            }
        });

        jBtnInventario.setText("Inventario");
        jBtnInventario.setFocusable(false);
        jBtnInventario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnInventario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInventarioActionPerformed(evt);
            }
        });

        jInternalFramePrincipal.setVisible(true);

        javax.swing.GroupLayout jInternalFramePrincipalLayout = new javax.swing.GroupLayout(jInternalFramePrincipal.getContentPane());
        jInternalFramePrincipal.getContentPane().setLayout(jInternalFramePrincipalLayout);
        jInternalFramePrincipalLayout.setHorizontalGroup(
            jInternalFramePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFramePrincipalLayout.setVerticalGroup(
            jInternalFramePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jInternalFramePrincipal)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnStock, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 475, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnProveedores, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnInventario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnStock)
                    .addComponent(jBtnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jInternalFramePrincipal)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBtnInventario, jBtnProductos, jBtnProveedores, jBtnStock});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProductosActionPerformed
        irAProductos();
    }//GEN-LAST:event_jBtnProductosActionPerformed

    private void jBtnStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnStockActionPerformed
        irAStock();
    }//GEN-LAST:event_jBtnStockActionPerformed

    private void jBtnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProveedoresActionPerformed
        irAProveedores();
    }//GEN-LAST:event_jBtnProveedoresActionPerformed

    private void jBtnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInventarioActionPerformed
        irAInventario();
    }//GEN-LAST:event_jBtnInventarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnInventario;
    private javax.swing.JButton jBtnProductos;
    private javax.swing.JButton jBtnProveedores;
    private javax.swing.JButton jBtnStock;
    private javax.swing.JInternalFrame jInternalFramePrincipal;
    // End of variables declaration//GEN-END:variables

    public void irAProductos() {
        setGreyButtons();
        jBtnProductos.setBackground(COLOR_BTN_ACTIVO);
        setFullSizeJInternalFrame(Formularios.PRODUCTOS);
    }

    private void irAInventario() {
        setGreyButtons();
        jBtnInventario.setBackground(COLOR_BTN_ACTIVO);
        setFullSizeJInternalFrame(Formularios.INVENTARIO);
    }

    private void irAProveedores() {
        setGreyButtons();
        jBtnProveedores.setBackground(COLOR_BTN_ACTIVO);
        setFullSizeJInternalFrame(Formularios.PROVEEDORES);
    }

    private void irAStock() {
        setGreyButtons();
        jBtnStock.setBackground(COLOR_BTN_ACTIVO);
        setFullSizeJInternalFrame(Formularios.STOCK);
    }

    private void inicializar() {
        setGreyButtons();
        frmProductosDetalle frmProductosDetalle = new frmProductosDetalle();
        jInternalFramePrincipal.add(frmProductosDetalle);

        frmOperacionStock frmOperacionStock = new frmOperacionStock();
        jInternalFramePrincipal.add(frmOperacionStock);

        mapFormularios.put(Formularios.PRODUCTOS, frmProductosDetalle);
        mapFormularios.put(Formularios.INVENTARIO, frmProductosDetalle);
        mapFormularios.put(Formularios.PROVEEDORES, frmProductosDetalle);
        mapFormularios.put(Formularios.STOCK, frmOperacionStock);

    }

    private void setGreyButtons() {
        final java.awt.Color color = java.awt.Color.gray;
        jBtnInventario.setBackground(color);
        jBtnProductos.setBackground(color);
        jBtnStock.setBackground(color);
        jBtnProveedores.setBackground(color);

    }

    private void setFullSizeJInternalFrame(Formularios formulario) {

        for (Formularios form : Formularios.values()) {
            mapFormularios.get(form).setVisible(false);
        }

        Dimension d = jInternalFramePrincipal.getSize();
        mapFormularios.get(formulario).setVisible(true);
        mapFormularios.get(formulario).setSize(d.width, d.height);
    }
}
