/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import util.UIHelper;

/**
 *
 * @author Diego Sebastian
 */
public class frmPrincipal extends javax.swing.JFrame {

    private static final java.awt.Color COLOR_BTN_ACTIVO = Color.getHSBColor(128, 255, 128);

    private enum Formularios {
        PUNTO_VENTA,
        TRABAJADORES,
        PRODUCTOS,
        STOCK,
        PROVEEDORES
    }

    private static HashMap<Formularios, JInternalFrame> mapFormularios;

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {

        initComponents();
        inicializar();
        bindKeys();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnRegistroTrabajadores = new javax.swing.JButton();
        jbtnRegistroProductos = new javax.swing.JButton();
        jbtnIngresoStock = new javax.swing.JButton();
        jbtnPuntoVenta = new javax.swing.JButton();
        jbtnRegistroProveedores = new javax.swing.JButton();
        jDesktopPanePrincipal = new javax.swing.JDesktopPane();
        jInternalFramePrincipal = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de relación con clientes (CRM)");

        jbtnRegistroTrabajadores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnRegistroTrabajadores.setText("<html><p><u style=\"font-weight:bold\">T</u>rabajadores</p></html>");
        jbtnRegistroTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistroTrabajadoresActionPerformed(evt);
            }
        });

        jbtnRegistroProductos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnRegistroProductos.setText("<html><p><u style=\"font-weight:bold\">P</u>roductos</p></html>");
        jbtnRegistroProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistroProductosActionPerformed(evt);
            }
        });

        jbtnIngresoStock.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnIngresoStock.setText("<html><p><u style=\"font-weight:bold\">S</u>tock</p></html>");
        jbtnIngresoStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIngresoStockActionPerformed(evt);
            }
        });

        jbtnPuntoVenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnPuntoVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/venta_32.png"))); // NOI18N
        jbtnPuntoVenta.setText("<html><p><u style=\"font-weight:bold\">V</u>entas</p><p style=\"text-align: center;\"></html>");
        jbtnPuntoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPuntoVentaActionPerformed(evt);
            }
        });

        jbtnRegistroProveedores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnRegistroProveedores.setText("<html><p>Pr<u style=\"font-weight:bold\">o</u>veedores</p></html>");
        jbtnRegistroProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistroProveedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPanePrincipalLayout = new javax.swing.GroupLayout(jDesktopPanePrincipal);
        jDesktopPanePrincipal.setLayout(jDesktopPanePrincipalLayout);
        jDesktopPanePrincipalLayout.setHorizontalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPanePrincipalLayout.setVerticalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jInternalFramePrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jInternalFramePrincipal.setPreferredSize(new java.awt.Dimension(1000, 600));
        jInternalFramePrincipal.setVisible(true);

        javax.swing.GroupLayout jInternalFramePrincipalLayout = new javax.swing.GroupLayout(jInternalFramePrincipal.getContentPane());
        jInternalFramePrincipal.getContentPane().setLayout(jInternalFramePrincipalLayout);
        jInternalFramePrincipalLayout.setHorizontalGroup(
            jInternalFramePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFramePrincipalLayout.setVerticalGroup(
            jInternalFramePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnRegistroProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnIngresoStock, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnRegistroProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnRegistroTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPuntoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1025, 1025, 1025)
                        .addComponent(jDesktopPanePrincipal))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInternalFramePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 999, Short.MAX_VALUE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jDesktopPanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnPuntoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnRegistroTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnRegistroProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jbtnIngresoStock, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnRegistroProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jInternalFramePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnRegistroTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistroTrabajadoresActionPerformed

    }//GEN-LAST:event_jbtnRegistroTrabajadoresActionPerformed

    private void jbtnRegistroProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistroProductosActionPerformed

    }//GEN-LAST:event_jbtnRegistroProductosActionPerformed

    private void jbtnIngresoStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIngresoStockActionPerformed

    }//GEN-LAST:event_jbtnIngresoStockActionPerformed

    private void jbtnPuntoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPuntoVentaActionPerformed

    }//GEN-LAST:event_jbtnPuntoVentaActionPerformed

    private void jbtnRegistroProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistroProveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnRegistroProveedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPanePrincipal;
    private javax.swing.JInternalFrame jInternalFramePrincipal;
    private javax.swing.JButton jbtnIngresoStock;
    private javax.swing.JButton jbtnPuntoVenta;
    private javax.swing.JButton jbtnRegistroProductos;
    private javax.swing.JButton jbtnRegistroProveedores;
    private javax.swing.JButton jbtnRegistroTrabajadores;
    // End of variables declaration//GEN-END:variables

    private void registroTrabajadores() {
        setFullSizeJInternalFrame(Formularios.TRABAJADORES);
        jInternalFramePrincipal.setTitle("Trabajadores");
        setGreyButtons();
        jbtnRegistroTrabajadores.setBackground(COLOR_BTN_ACTIVO);
    }

    private void registroProductos() {
        setFullSizeJInternalFrame(Formularios.PRODUCTOS);
        jInternalFramePrincipal.setTitle("Productos");
        setGreyButtons();
        jbtnRegistroProductos.setBackground(COLOR_BTN_ACTIVO);
    }

    private void ingresoStock() {
        setFullSizeJInternalFrame(Formularios.STOCK);
        jInternalFramePrincipal.setTitle("Stock productos");
        setGreyButtons();
        jbtnIngresoStock.setBackground(COLOR_BTN_ACTIVO);
    }

    private void puntoVenta() {
        setFullSizeJInternalFrame(Formularios.PUNTO_VENTA);
        jInternalFramePrincipal.setTitle("Punto de venta");
        setGreyButtons();
        jbtnPuntoVenta.setBackground(COLOR_BTN_ACTIVO);
    }

    private void registroProveedor() {
        setFullSizeJInternalFrame(Formularios.PROVEEDORES);
        jInternalFramePrincipal.setTitle("Proveedores");
        setGreyButtons();
        jbtnRegistroProveedores.setBackground(COLOR_BTN_ACTIVO);
    }

    private void setFullSizeJInternalFrame(Formularios formulario) {

        for (Formularios form : Formularios.values()) {
            mapFormularios.get(form).setVisible(false);
        }

        Dimension d = jInternalFramePrincipal.getSize();
        mapFormularios.get(formulario).setVisible(true);
        mapFormularios.get(formulario).setSize(d.width, d.height);
    }

    private void setGreyButtons() {
        final java.awt.Color color = java.awt.Color.gray;
        jbtnRegistroTrabajadores.setBackground(color);
        jbtnRegistroProductos.setBackground(color);
        jbtnIngresoStock.setBackground(color);
        jbtnRegistroProveedores.setBackground(color);
        jbtnPuntoVenta.setBackground(color);
    }

    private void inicializar() {
        setGreyButtons();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        jInternalFramePrincipal.putClientProperty("JInternalFrame.isPalette", Boolean.TRUE);
        jInternalFramePrincipal.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        jInternalFramePrincipal.repaint();
        getContentPane().setBackground(new java.awt.Color(236, 236, 236));

        mapFormularios = new HashMap<>();

        frmPuntoVenta frmPuntoVenta = new frmPuntoVenta();
        frmPuntoVenta.setLocation(-1, -24);
        jInternalFramePrincipal.add(frmPuntoVenta);

        frmRegistroTrabajadores frmRegistroTrabajadores = new frmRegistroTrabajadores();
        frmRegistroTrabajadores.setLocation(-1, -24);
        jInternalFramePrincipal.add(frmRegistroTrabajadores);

        frmRegistroProductos frmRegistroProductos = new frmRegistroProductos();
        frmRegistroProductos.setLocation(-1, -24);
        jInternalFramePrincipal.add(frmRegistroProductos);

        frmIngresoStock frmIngresoStock = new frmIngresoStock();
        frmIngresoStock.setLocation(-1, -24);
        jInternalFramePrincipal.add(frmIngresoStock);

        frmRegistroProveedor frmRegistroProveedor = new frmRegistroProveedor();
        frmRegistroProveedor.setLocation(-1, -24);
        jInternalFramePrincipal.add(frmRegistroProveedor);

        mapFormularios.put(Formularios.PUNTO_VENTA, frmPuntoVenta);
        mapFormularios.put(Formularios.TRABAJADORES, frmRegistroTrabajadores);
        mapFormularios.put(Formularios.PRODUCTOS, frmRegistroProductos);
        mapFormularios.put(Formularios.STOCK, frmIngresoStock);
        mapFormularios.put(Formularios.PROVEEDORES, frmRegistroProveedor);
    }

    private void bindKeys() {
        Action shiftT = new AbstractAction(
                "<html><p><u style=\"font-weight:bold\">T</u>rabajadores</p></html>",
                new ImageIcon(getClass().getResource("/resources/empleados_32.png"))
        ) {
            @Override
            public void actionPerformed(ActionEvent e) {
                registroTrabajadores();
            }
        };
        Action shiftP = new AbstractAction(
                "<html><p><u style=\"font-weight:bold\">P</u>roductos</p></html>",
                new ImageIcon(getClass().getResource("/resources/caja_32.png"))
        ) {
            @Override
            public void actionPerformed(ActionEvent e
            ) {
                registroProductos();
            }
        };
        Action shiftS = new AbstractAction(
                "<html><p><u style=\"font-weight:bold\">S</u>tock</p></html>",
                new ImageIcon(getClass().getResource("/resources/almacen_32.png"))) {
            @Override
            public void actionPerformed(ActionEvent e) {
                ingresoStock();
            }
        };
        Action shiftV = new AbstractAction(
                "<html><p><u style=\"font-weight:bold\">V</u>entas</p><p style=\"text-align: center;\"></html>",
                new ImageIcon(getClass().getResource("/resources/venta_32.png"))) {
            @Override
            public void actionPerformed(ActionEvent e) {
                puntoVenta();
            }
        };
        Action shiftO = new AbstractAction(
                "<html><p>Pr<u style=\"font-weight:bold\">o</u>veedores</p></html>",
                new ImageIcon(getClass().getResource("/resources/proveedor_32.png"))) {
            @Override
            public void actionPerformed(ActionEvent e) {
                registroProveedor();
            }
        };

        UIHelper.bindKeyToButton(jbtnRegistroTrabajadores, shiftT, KeyStroke.getKeyStroke(KeyEvent.VK_T, InputEvent.SHIFT_MASK));
        UIHelper.bindKeyToButton(jbtnRegistroProductos, shiftP, KeyStroke.getKeyStroke(KeyEvent.VK_P, InputEvent.SHIFT_MASK));
        UIHelper.bindKeyToButton(jbtnIngresoStock, shiftS, KeyStroke.getKeyStroke(KeyEvent.VK_S, InputEvent.SHIFT_MASK));
        UIHelper.bindKeyToButton(jbtnPuntoVenta, shiftV, KeyStroke.getKeyStroke(KeyEvent.VK_V, InputEvent.SHIFT_MASK));
        UIHelper.bindKeyToButton(jbtnRegistroProveedores, shiftO, KeyStroke.getKeyStroke(KeyEvent.VK_O, InputEvent.SHIFT_MASK));

    }

}
