/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import business.ProductosController;
import static complements.Constants.PATH_RECURSOS;
import complements.DataReader;
import complements.OnlyDigitWithDecimalsAdapter;
import components.FileTypeFilter;
import components.JComboBoxAddItemsField;
import components.JFocusedTextField;
import java.awt.Checkbox;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import static javax.swing.JOptionPane.showMessageDialog;
import util.UIHelper;

/**
 *
 * @author Diego Sebastian
 */
public class frmRegistroProductos extends javax.swing.JFrame {

    private static final ProductosController productosController = new ProductosController();
    private File fileToSave = null;
    private HashMap<Integer, String> hashMapCategoria;
    private HashMap<Integer, String> hashMapMarca;
    private final MasterJInternalFrame parent;

    /**
     * Creates new form frmRegistroProductos
     *
     * @param parent
     */
    public frmRegistroProductos(MasterJInternalFrame parent) {
        initComponents();
        this.parent = parent;
        super.setExtendedState(JFrame.MAXIMIZED_BOTH);

        inicializar();


        /*jTxtCodigo.setDocument(new JTextFieldLimit(20));
        jTxtNombreProducto.setDocument(new JTextFieldLimit(45));
        jTxtPrecioUnitario.setDocument(new JTextFieldLimit(15));

         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnGuardar = new javax.swing.JButton();
        jPanelControles = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtCodigoProducto = new JFocusedTextField(java.awt.Color.yellow,java.awt.Color.blue);
        jLabel2 = new javax.swing.JLabel();
        jTxtDescripcion = new JFocusedTextField(java.awt.Color.yellow,java.awt.Color.blue);
        checkCodigo = new java.awt.Checkbox();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxCategoria = new JComboBoxAddItemsField();
        jBtnAgregarCategoria = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxMarca = new JComboBoxAddItemsField();
        jBtnAgregarMarca = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jTxtPrecioVenta = new JFocusedTextField(java.awt.Color.yellow,java.awt.Color.blue);
        jLabel6 = new javax.swing.JLabel();
        jTxtPrecioCosto = new JFocusedTextField(java.awt.Color.yellow,java.awt.Color.blue);
        checkPrecioVenta = new java.awt.Checkbox();
        checkPrecioVentaCambiarPrecio = new java.awt.Checkbox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxtCodigo = new JFocusedTextField(java.awt.Color.yellow,java.awt.Color.blue);
        jTxtCodigoProducto5 = new JFocusedTextField(java.awt.Color.yellow,java.awt.Color.blue);
        jLabel9 = new javax.swing.JLabel();
        jTxtCodigoBarras = new JFocusedTextField(java.awt.Color.yellow,java.awt.Color.blue);
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jTxtStock = new JFocusedTextField(java.awt.Color.yellow,java.awt.Color.blue);
        jLabel11 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtObservaciones = new java.awt.TextArea();
        jPanelImagen = new javax.swing.JPanel();
        jLblTextoImagen = new javax.swing.JLabel();
        jLblImagen = new javax.swing.JLabel();
        jPanelGanancia = new javax.swing.JPanel();
        jTxtGanancia = new JFocusedTextField(java.awt.Color.yellow,java.awt.Color.blue);
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLblCancelar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setTitle("Registro Productos");

        jBtnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnGuardar.setText("<html>Guardar (F2)</html>");
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Código");

        jTxtCodigoProducto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTxtCodigoProducto.setMargin(new java.awt.Insets(2, 5, 2, 2));
        jTxtCodigoProducto.setMinimumSize(new java.awt.Dimension(150, 35));
        jTxtCodigoProducto.setPreferredSize(new java.awt.Dimension(150, 35));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Descripción");

        jTxtDescripcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTxtDescripcion.setMargin(new java.awt.Insets(2, 5, 2, 2));
        jTxtDescripcion.setMinimumSize(new java.awt.Dimension(150, 35));
        jTxtDescripcion.setPreferredSize(new java.awt.Dimension(150, 35));

        checkCodigo.setLabel("Automático");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Categoría");

        jComboBoxCategoria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxCategoria.setMinimumSize(new java.awt.Dimension(170, 35));
        jComboBoxCategoria.setName(""); // NOI18N
        jComboBoxCategoria.setPreferredSize(new java.awt.Dimension(170, 35));

        jBtnAgregarCategoria.setText("Agregar");
        jBtnAgregarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarCategoriaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Marca");

        jComboBoxMarca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxMarca.setMinimumSize(new java.awt.Dimension(170, 35));
        jComboBoxMarca.setName(""); // NOI18N
        jComboBoxMarca.setPreferredSize(new java.awt.Dimension(170, 35));

        jBtnAgregarMarca.setText("Agregar");
        jBtnAgregarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarMarcaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Precio de venta");

        jTxtPrecioVenta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTxtPrecioVenta.setMargin(new java.awt.Insets(2, 5, 2, 2));
        jTxtPrecioVenta.setMinimumSize(new java.awt.Dimension(150, 35));
        jTxtPrecioVenta.setPreferredSize(new java.awt.Dimension(150, 35));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Precio de costo");

        jTxtPrecioCosto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTxtPrecioCosto.setMargin(new java.awt.Insets(2, 5, 2, 2));
        jTxtPrecioCosto.setMinimumSize(new java.awt.Dimension(150, 35));
        jTxtPrecioCosto.setPreferredSize(new java.awt.Dimension(150, 35));

        checkPrecioVenta.setLabel("Automático");

        checkPrecioVentaCambiarPrecio.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        checkPrecioVentaCambiarPrecio.setLabel("Permitir cambiar el precio en el momento de la venta");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Peso bruto");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Peso líquido");

        jTxtCodigo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTxtCodigo.setMargin(new java.awt.Insets(2, 5, 2, 2));
        jTxtCodigo.setMinimumSize(new java.awt.Dimension(150, 35));
        jTxtCodigo.setPreferredSize(new java.awt.Dimension(150, 35));

        jTxtCodigoProducto5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTxtCodigoProducto5.setMargin(new java.awt.Insets(2, 5, 2, 2));
        jTxtCodigoProducto5.setMinimumSize(new java.awt.Dimension(150, 35));
        jTxtCodigoProducto5.setPreferredSize(new java.awt.Dimension(150, 35));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Código de barras");

        jTxtCodigoBarras.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTxtCodigoBarras.setMargin(new java.awt.Insets(2, 5, 2, 2));
        jTxtCodigoBarras.setMinimumSize(new java.awt.Dimension(150, 35));
        jTxtCodigoBarras.setPreferredSize(new java.awt.Dimension(150, 35));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Stock actual");

        jTxtStock.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTxtStock.setMargin(new java.awt.Insets(2, 5, 2, 2));
        jTxtStock.setMinimumSize(new java.awt.Dimension(150, 35));
        jTxtStock.setPreferredSize(new java.awt.Dimension(150, 35));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel11.setText("Observaciones");

        jPanelImagen.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLblTextoImagen.setForeground(new java.awt.Color(153, 153, 153));
        jLblTextoImagen.setText("<html><style> h1 {text-align: center;} p {text-align: center;} </style><p>Clic aquí para elegir una foto</p><p>para este producto</p></html>");

        jLblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/camara.png"))); // NOI18N

        javax.swing.GroupLayout jPanelImagenLayout = new javax.swing.GroupLayout(jPanelImagen);
        jPanelImagen.setLayout(jPanelImagenLayout);
        jPanelImagenLayout.setHorizontalGroup(
            jPanelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImagenLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLblTextoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addComponent(jLblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelImagenLayout.setVerticalGroup(
            jPanelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelImagenLayout.createSequentialGroup()
                .addComponent(jLblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLblTextoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTxtGanancia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTxtGanancia.setMargin(new java.awt.Insets(2, 5, 2, 2));
        jTxtGanancia.setMinimumSize(new java.awt.Dimension(150, 35));
        jTxtGanancia.setPreferredSize(new java.awt.Dimension(150, 35));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setText("Margen ganancia");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel15.setText("(porcentaje)");

        javax.swing.GroupLayout jPanelGananciaLayout = new javax.swing.GroupLayout(jPanelGanancia);
        jPanelGanancia.setLayout(jPanelGananciaLayout);
        jPanelGananciaLayout.setHorizontalGroup(
            jPanelGananciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGananciaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTxtGanancia, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelGananciaLayout.setVerticalGroup(
            jPanelGananciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGananciaLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanelGananciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtGanancia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout jPanelControlesLayout = new javax.swing.GroupLayout(jPanelControles);
        jPanelControles.setLayout(jPanelControlesLayout);
        jPanelControlesLayout.setHorizontalGroup(
            jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlesLayout.createSequentialGroup()
                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelControlesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanelControlesLayout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(txtObservaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(3, 3, 3))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelControlesLayout.createSequentialGroup()
                                    .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, 0)
                                    .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelControlesLayout.createSequentialGroup()
                                            .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanelControlesLayout.createSequentialGroup()
                                                    .addComponent(jComboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jBtnAgregarMarca))
                                                .addGroup(jPanelControlesLayout.createSequentialGroup()
                                                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jBtnAgregarCategoria)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelControlesLayout.createSequentialGroup()
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jTxtCodigoProducto5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelControlesLayout.createSequentialGroup()
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jTxtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(jTxtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanelControlesLayout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(checkCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(jTxtCodigoBarras, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                                .addGroup(jPanelControlesLayout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(jTxtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelControlesLayout.createSequentialGroup()
                                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanelGanancia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelControlesLayout.createSequentialGroup()
                                        .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanelControlesLayout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(jTxtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanelControlesLayout.createSequentialGroup()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(jTxtPrecioCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(checkPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(120, 120, 120))))
                    .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(checkPrecioVentaCambiarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addComponent(jPanelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelControlesLayout.setVerticalGroup(
            jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelControlesLayout.createSequentialGroup()
                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelControlesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(checkCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTxtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelControlesLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtCodigoBarras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnAgregarCategoria)
                        .addComponent(jTxtCodigoProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboBoxMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnAgregarMarca, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTxtCodigoProducto5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelControlesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelControlesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTxtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelControlesLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(checkPrecioVentaCambiarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelControlesLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(checkPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelGanancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtPrecioCosto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelControlesLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(110, 110, 110))
                    .addGroup(jPanelControlesLayout.createSequentialGroup()
                        .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
            .addGroup(jPanelControlesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLblCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLblCancelar.setText("<html><u>Cancelar</u></html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLblCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanelControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed

    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void jBtnAgregarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarCategoriaActionPerformed
        agregarCategoria();
    }//GEN-LAST:event_jBtnAgregarCategoriaActionPerformed

    private void jBtnAgregarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarMarcaActionPerformed
        agregarMarca();
    }//GEN-LAST:event_jBtnAgregarMarcaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Checkbox checkCodigo;
    private java.awt.Checkbox checkPrecioVenta;
    private java.awt.Checkbox checkPrecioVentaCambiarPrecio;
    private javax.swing.JButton jBtnAgregarCategoria;
    private javax.swing.JButton jBtnAgregarMarca;
    private javax.swing.JButton jBtnGuardar;
    private javax.swing.JComboBox<Map.Entry<Integer,String>> jComboBoxCategoria;
    private javax.swing.JComboBox<Map.Entry<Integer,String>> jComboBoxMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblCancelar;
    private javax.swing.JLabel jLblImagen;
    private javax.swing.JLabel jLblTextoImagen;
    private javax.swing.JPanel jPanelControles;
    private javax.swing.JPanel jPanelGanancia;
    private javax.swing.JPanel jPanelImagen;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTxtCodigo;
    private javax.swing.JTextField jTxtCodigoBarras;
    private javax.swing.JTextField jTxtCodigoProducto;
    private javax.swing.JTextField jTxtCodigoProducto5;
    private javax.swing.JTextField jTxtDescripcion;
    private javax.swing.JTextField jTxtGanancia;
    private javax.swing.JTextField jTxtPrecioCosto;
    private javax.swing.JTextField jTxtPrecioVenta;
    private javax.swing.JTextField jTxtStock;
    private java.awt.TextArea txtObservaciones;
    // End of variables declaration//GEN-END:variables

    private void inicializar() {
        hashMapCategoria = new HashMap<>();
        hashMapMarca = new HashMap<>();
        hashMapCategoria.put(0, "-------------------");
        hashMapMarca.put(0, "-------------------");

        productosController.listarCategoriasProducto().forEach(x -> {
            hashMapCategoria.put(x.getCodigo(), x.getNombre());
        });

        productosController.listarMarcas().forEach(x -> {
            hashMapMarca.put(x.getCodigo(), x.getNombre());
        });

        hashMapCategoria.entrySet().forEach((entry) -> {
            jComboBoxCategoria.addItem(entry);
        });

        hashMapMarca.entrySet().forEach((entry) -> {
            jComboBoxMarca.addItem(entry);
        });

        jPanelGanancia.setVisible(false);

        checkCodigo.addItemListener((ItemEvent e) -> {
            jTxtCodigo.setEnabled(!((Checkbox) e.getSource()).getState());
            if (!jTxtCodigo.isEnabled()) {
                jTxtCodigo.setText("");
            }
        });

        checkPrecioVenta.addItemListener((ItemEvent e) -> {
            boolean checked = ((Checkbox) e.getSource()).getState();
            jPanelGanancia.setVisible(checked);
            jTxtPrecioVenta.setEnabled(!checked);
            if (checked) {
                jTxtGanancia.setText("");
            }
        });

        addListenerImage();

        jTxtPrecioVenta.addKeyListener(new OnlyDigitWithDecimalsAdapter());
        jTxtGanancia.addKeyListener(new OnlyDigitWithDecimalsAdapter());
        jTxtPrecioCosto.addKeyListener(new OnlyDigitWithDecimalsAdapter());

        Action actionF2 = new AbstractAction(
                "<html>Guardar (F2)</html>") {
            @Override
            public void actionPerformed(ActionEvent e) {
                guardar();
            }
        };
        UIHelper.bindKeyToButton(jBtnGuardar, actionF2, "F2");
    }

    private void addListenerImage() {
        jLblImagen.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                openImagePicker();
            }
        });

        jLblTextoImagen.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                openImagePicker();
            }
        });
    }

    private void openImagePicker() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("D:/"));

        FileTypeFilter filterJPG = new FileTypeFilter(".jpg", "JPEG Images");
        fileChooser.addChoosableFileFilter(filterJPG);
        FileTypeFilter filterPNG = new FileTypeFilter(".png", "PNG Images");
        fileChooser.addChoosableFileFilter(filterPNG);

        fileChooser.setDialogTitle("Elija una imagen para el producto");
        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {

            fileToSave = fileChooser.getSelectedFile();
            ImageIcon icono = new ImageIcon(fileChooser.getSelectedFile().getPath());
            icono = new ImageIcon(icono.getImage().getScaledInstance(191, 191, Image.SCALE_SMOOTH));

            jLblTextoImagen.setVisible(false);
            jLblImagen.setIcon(icono);
            jLblImagen.setSize(191, 191);
            jPanelImagen.setSize(191, 191);
        }
    }

    private void guardar() {
        boolean esValido = true;
        if (jTxtCodigo.getText().isEmpty() && checkCodigo.getState() == false) {
            esValido = false;
            jTxtCodigo.requestFocus();
        } else if (jTxtDescripcion.getText().isEmpty()) {
            esValido = false;
            jTxtDescripcion.requestFocus();
        } else if (jComboBoxCategoria.getSelectedIndex() == 0) {
            esValido = false;
        } else if (jComboBoxMarca.getSelectedIndex() == 0) {
            esValido = false;
        }

        if (!esValido) {
            showMessageDialog(this, "Ingrese todos los datos correctamente.");
        } else {
            String imagePath = "";
            if (fileToSave != null) {
                imagePath = PATH_RECURSOS + fileToSave.getName();
            }
            productosController.
                    agregarProducto(
                            checkCodigo.getState(),
                            jTxtCodigo.getText(),
                            jTxtDescripcion.getText(),
                            Double.parseDouble(jTxtPrecioVenta.getText()),
                            Double.parseDouble(jTxtPrecioCosto.getText()),
                            checkPrecioVentaCambiarPrecio.getState(),
                            imagePath,
                            jTxtCodigoBarras.getText(),
                            ((Map.Entry<Integer, Object>) jComboBoxCategoria.getSelectedItem()).getKey(),
                            ((Map.Entry<Integer, Object>) jComboBoxMarca.getSelectedItem()).getKey());

            if (fileToSave != null) {
                File destinationFile = new File(
                        DataReader.getUsersProjectRootDirectory()
                        + imagePath
                );
                try {
                    DataReader.copyFile(fileToSave, destinationFile);
                } catch (IOException ex) {
                    System.out.println("Error al grabar " + ex);
                }
            }

            parent.onChildClosing();
            this.dispose();
        }

    }

    private void agregarMarca() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void agregarCategoria() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
